### ISSUE TITLE
Method live was removed on jQuery 1.9

### ISSUE THREAD

**Issue by willianrodrigues** [malihu/jquery-style-my-tooltips#2]
Hello,

I just want to let you know that the method "live" used in you plugins is no more available in jQuery 1.9. If you could, please fix this issue.

Thank you!

**Comment by malihu** [comment]
Yes I'm aware of it but I'm not really sure when I'll be able to find time to update it... 

If you want to try editing the js, change (line 38): 

from: 
`return this["live"]("mouseover",function(event){`

to: 
`return $("body")["delegate"](this.selector,"mouseover",function(event){`

and line 26, from: 
`$(".smt-current-element").live("mouseout mousedown click",function(){`

to: 
`$("body").delegate(".smt-current-element","mouseout mousedown click",function(){`

Haven't tried this but it should work :)

**Comment by willianrodrigues** [comment]
Unfortunatelly, It didn't work. I'll try to fix it.

Thank you.

EDIT: Sorry, I forgot to apply one of your comment. It's working fine now. Thank you again!
