### ISSUE TITLE
Only works on elements loaded on start

### ISSUE THREAD

**Issue by OmgImAlexis** [malihu/jquery-style-my-tooltips#6]
As you can see on my [blog](reblogalert.tumblr.com) the tooltips don't work at all on new posts once you scroll down even though they should.

**Comment by malihu** [comment]
Can you re-call the function below each time you load new contents? 
`$(".post.photo[title]").style_my_tooltips({tip_follows_cursor: true, tip_delay_time: 50});`

**Comment by OmgImAlexis** [comment]
That seems to just disable it.
My guess is that it removes the title so nothing happens on hover. I'll have a look into this tomorrow, I have a feeling I may be able to get it working again. It's 5AM here so I need sleep.

BTW the code is updated on there, have a look at [this](https://s3.amazonaws.com/static.tumblr.com/ib6vvvn/64bnhxcdq/pageload.js) script, it's what's responsible for my infinite scroll, the edit is around line 120.

EDIT: Wrong link, fixed.
